# Generated by Django 4.2.2 on 2023-06-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="address_line1",),
        migrations.RemoveField(model_name="userprofile", name="address_line2",),
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
